"""
Bochum Gladbach 03-18-2022 xg Bochum 1.66, xg BMG 0.62
Verona Roma 09-19-2020 xg Verona 0.91 xg Roma 1.78
Ligue 1 from 03-13-2020 all matches cancelled - deleted in my fixtures csv
"""

league_mapping = {
    "Bundesliga": "buli",
    "Premier League": "epl",
    "La Liga": "laliga",
    "Ligue 1": "ligue1",
    "Serie A": "seriea",
}
STATS_ABBREVIATIONS = {
"progressive_passes" : "PrPa",
"progressive_carries":"PrCa",
"challenge_tackles_pct" : "TcklPct"
}
META_COLUMNS = ["home_team", "away_team", "outcome", "date", "season", "gameweek"]
ODDS_COLUMNS = ["b365h","b365d","b365a"]

DEFENSIVE_STATS = ["tackles","blocks","blocked_shots","blocked_passes","interceptions","ball_recoveries","aerials_won"]
OFFENSIVE_STATS = ["crosses","progressive_carries","progressive_passes","sca"]

FOOTBALL_DATA_INTERESTING_COLUMNS = [
    "date",
    "home_team",
    "away_team",
    "b365h",
    "b365d",
    "b365a",
]
team_name_mapping = {
    "Arminia": "Arminia Bielefeld",
    "Augsburg": "FC Augsburg",
    "Freiburg": "SC Freiburg",
    "Leverkusen": "Bayer Leverkusen",
    "Dortmund": "Borussia Dortmund",
    "1. FC Köln": "FC Cologne",
    "Köln": "FC Cologne",
    "Cologne": "FC Cologne",
    "FC Koln": "FC Cologne",
    "RasenBallsport Leipzig": "RB Leipzig",
    "Eint Frankfurt": "Eintracht Frankfurt",
    "Ein Frankfurt": "Eintracht Frankfurt",
    "Hertha Berlin": "Hertha BSC Berlin",
    "Hertha BSC": "Hertha BSC Berlin",
    "Hertha": "Hertha BSC Berlin",
    "Stuttgart": "VfB Stuttgart",
    "Hoffenheim": "TSG Hoffenheim",
    "1899 Hoffenheim": "TSG Hoffenheim",
    "M'Gladbach": "Borussia M.Gladbach",
    "M'gladbach": "Borussia M.Gladbach",
    "B. Monchengladbach": "Borussia M.Gladbach",
    "Borussia Gladbach": "Borussia M.Gladbach",
    "Mönchengladbach": "Borussia M.Gladbach",
    "Wolfsburg": "VfL Wolfsburg",
    "Bochum": "VfL Bochum",
    "1. FC Union Berlin": "Union Berlin",
    "Darmstadt 98": "Darmstadt",
    "Ingolstadt 04": "FC Ingolstadt",
    "Ingolstadt": "FC Ingolstadt",
    "Mainz": "FSV Mainz",
    "Mainz 05": "FSV Mainz",
    "FSV Mainz 05": "FSV Mainz",
    "Hamburg": "Hamburger SV",
    "Hannover": "Hannover 96",
    "Nurnberg": "FC Nuernberg",
    "Nuernberg": "FC Nuernberg",
    "Nürnberg": "FC Nuernberg",
    "Düsseldorf": "Fortuna Duesseldorf",
    "Fortuna Dusseldorf": "Fortuna Duesseldorf",
    "Paderborn": "SC Paderborn",
    "Paderborn 07": "SC Paderborn",
    "Schalke": "FC Schalke 04",
    "Schalke 04": "FC Schalke 04",
    "Greuther Fürth": "Greuther Fuerth",
    "Greuther Furth": "Greuther Fuerth",
    "Bielefeld": "Arminia Bielefeld",
    "Newcastle Utd": "Newcastle United",
    "Newcastle": "Newcastle United",
    "Wolverhampton":"Wolverhampton Wanderers",
    "Wolves": "Wolverhampton Wanderers",
    "Tottenham Hotspur":"Tottenham",
    "Manchester Utd": "Manchester United",
    "Man United": "Manchester United",
    "Man City": "Manchester City",
    "Norwich": "Norwich City",
    "Leicester": "Leicester City",
    "Leeds": "Leeds United",
    "Hull": "Hull City",
    "Stoke": "Stoke City",
    "Swansea": "Swansea City",
    "AFC Bournemouth":"Bournemouth",
    "West Bromwich Albion": "West Brom",
    "West Ham United":"West Ham",
    "Cardiff": "Cardiff City",
    "Sheffield Utd": "Sheffield United",
    "Nott'ham Forest": "Nottingham Forest",
    "Nott'm Forest": "Nottingham Forest",
    "Nottingham":"Nottingham Forest",
    "La Coruna": "Deportivo La Coruna",
    "Ath Madrid": "Atletico Madrid",
    "Atl. Madrid": "Atletico Madrid",
    "Betis": "Real Betis",
    "Espanol": "Espanyol",
    "Sociedad": "Real Sociedad",
    "Sp Gijon": "Sporting Gijon",
    "Ath Bilbao": "Athletic Club",
    "Celta": "Celta Vigo",
    "Almería": "Almeria",
    "La Coruña": "Deportivo La Coruna",
    "Málaga": "Malaga",
    "Alavés": "Alaves",
    "Sporting Gijón": "Sporting Gijon",
    "Leganés": "Leganes",
    "Atlético Madrid": "Atletico Madrid",
    "Huesca": "SD Huesca",
    "Valladolid": "Real Valladolid",
    "Vallecano": "Rayo Vallecano",
    "Cádiz": "Cadiz",
    "Cadiz CF" : "Cadiz",
    "Milan": "AC Milan",
    "Verona": "Hellas Verona",
    "AS Roma": "Roma",
    "SPAL 2013": "SPAL",
    "Spal": "SPAL",
    "Parma Calcio 1913": "Parma Calcio",
    "Parma": "Parma Calcio",
    "Inter Milan": "Inter",
    "Bastia": "SC Bastia",
    "Paris Saint Germain": "Paris SG",
    "Paris S-G": "Paris SG",
    "Saint-Etienne": "St Etienne",
    "Saint-Étienne": "St Etienne",
}